### ISSUE TITLE
Cosign verify

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/harpoon#25]
As a security minded individual, I would like to be able to provide a cosign public key to ensure that an image has been signed before running in an environment.

AC:
Verify a public key can be provided to verify images
Verify that if a public key is provided and the signature does not match the image will not start
Verify that if a public key is not provided images launch as planned

**Comment by cooktheryan** [comment]
https://pkg.go.dev/github.com/sigstore/cosign/pkg/cosign#VerifyImageSignature

**Comment by sallyom** [comment]
I've updated this issue to verify git commits, instead - https://github.com/sigstore/gitsign has been officially released and it will offer what we need to verify what's being pulled into the system.

**Comment by sallyom** [comment]
Can now opt-in to sigstore/gitsign verify with  https://github.com/containers/fetchit/pull/224  and  https://github.com/containers/fetchit/pull/230, and with targetConfig like so:
```
targetConfigs:
- url: https://github.com/sallyom/fetchit
  verifyCommitsInfo:
    GitsignVerify: true
  filetransfer:
  - name: ft-ex
    targetPath: examples/filetransfer
    destinationDirectory: /tmp/ft
    schedule: "*/1 * * * *"
  branch: gitsign
```
